title: Smile Egbai
description: > # this means to ignore newlines until "baseurl:"
  Android engineer with 4+ years experience, have knowledge of kotlin, java and golang.
baseurl: # the subpath of your site, e.g. /blog
url: "https://smilecs.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Smile Egbai
tagline: Android Developer
about-description: Enthusiastic mobile developer, I love to solve challenges and provide value to people around me. I love novels(sci-fi) my favourites authors are J.k Rowling, Lori M and Patrick Rothfuss. Movies are welcome and play games(Fifa & Call of Duty). I think big and want to make a difference, it's not all about the code but the problem you can solve.
pic: img.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: mumene@gmail.com # Add your Email address
phone: 
website: https://past3.com.ng
linkedin: smilecs
github: smilecs
twitter: '@SmileEgbai' # Add your Twitter handle

# Tracker
analytics: UA-76641307-2

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
